### PR TITLE
Candle render modification

### PR DESCRIPTION
**Pull request by ghost**
Making candles render customizable and easier to read (in my opinion, but it can be changed)
Added colors support
Updated README with new screenshot of the final candles result

### CODE REVIEW

**Comment by mfontanini** [comment]
Wow that looks amazing! Can you just remove the binance config file you added? Nice to see _someone_ is using this :)

**Comment by Warlkiry** [comment]
Yeah sure, forgot this x)

**Comment by Warlkiry** [comment]
I will modify its GUI for now, I'll see if more things can be done once I'll be more used to the code structure :-)

**Comment by mfontanini** [comment]
Thanks!

**Pull request merged**
